"""The account and recordings API (app/routes/account.py) with its database and file storage.

Runs on in-memory SQLite with a stubbed Auth0 verifier (the bearer "token" is the user's sub),
so it needs neither Tiger Cloud nor an Auth0 tenant. Real token checking is covered by
test_auth_jwt.py.
"""

import io
import uuid

import numpy as np
import pytest
import soundfile
from sqlalchemy import event

from app import create_app
from app.extensions import db
from app.models import Recording, User


@pytest.fixture
def app(monkeypatch, tmp_path):
    import app.auth.dependencies as deps

    monkeypatch.setattr(deps, "verify_jwt", lambda token, **_: {"sub": token})

    application = create_app("testing")
    application.config.update(
        AUTH0_DOMAIN="test.auth0.com",
        AUTH0_API_AUDIENCE="https://api.test",
        STORAGE_DIR=str(tmp_path / "storage"),
    )
    with application.app_context():
        # SQLite leaves foreign keys off unless asked; Postgres always enforces them (ON DELETE CASCADE).
        event.listen(db.engine, "connect", lambda connection, _: connection.execute("PRAGMA foreign_keys=ON"))
        db.create_all()
    return application


@pytest.fixture
def client(app):
    return app.test_client()


def auth(sub):
    return {"Authorization": f"Bearer {sub}"}


def wav_bytes(seconds=0.5, rate=8000):
    buffer = io.BytesIO()
    soundfile.write(buffer, np.zeros(int(seconds * rate), dtype="float32"), rate, format="WAV")
    return buffer.getvalue()


def upload(client, sub, data=None, filename="song.wav", **fields):
    form = {"file": (io.BytesIO(wav_bytes() if data is None else data), filename), **fields}
    return client.post("/api/recordings", data=form, headers=auth(sub), content_type="multipart/form-data")


def user_count(app):
    with app.app_context():
        return db.session.scalar(db.select(db.func.count()).select_from(User))


# --- users ------------------------------------------------------------------------------------


def test_first_login_creates_exactly_one_user(app, client):
    r = client.get("/api/me", headers=auth("auth0|alice"))
    assert r.status_code == 200
    body = r.get_json()
    assert set(body) == {"id", "auth0_id", "created_at", "username", "display_name", "avatar_url"}
    assert body["auth0_id"] == "auth0|alice"
    assert body["username"] == "auth0_alice"  # access tokens only carry `sub`
    uuid.UUID(body["id"])  # a UUID, generated by the app
    assert user_count(app) == 1


def test_second_call_reuses_the_user(app, client):
    first = client.get("/api/me", headers=auth("auth0|alice")).get_json()
    second = client.get("/api/me", headers=auth("auth0|alice")).get_json()
    assert first == second
    assert user_count(app) == 1


def test_concurrent_first_logins_make_one_user(app, client, monkeypatch):
    """Two first requests both miss the lookup; the one that loses the insert reuses the winner's row."""
    import app.auth.dependencies as deps

    winner = client.get("/api/me", headers=auth("auth0|alice")).get_json()

    real_lookup = deps._user_by_auth0_id
    calls = []

    def lookup(sub):  # this request's first lookup ran before the other request's insert
        calls.append(sub)
        return None if len(calls) == 1 else real_lookup(sub)

    monkeypatch.setattr(deps, "_user_by_auth0_id", lookup)

    r = client.get("/api/me", headers=auth("auth0|alice"))
    assert r.status_code == 200
    assert r.get_json() == winner
    assert len(calls) == 2  # missed, lost the insert, then found the winner's row
    assert user_count(app) == 1


def test_two_people_racing_for_one_username_both_get_accounts(app, client, monkeypatch):
    """Bob's first username pick was free when he looked, but Alice took it before his insert."""
    import app.auth.dependencies as deps

    monkeypatch.setattr(deps, "verify_jwt", lambda token, **_: {"sub": token, "nickname": "sam"})
    alice = client.get("/api/me", headers=auth("auth0|alice")).get_json()
    assert alice["username"] == "sam"

    real_derive = deps._derive_username
    picks = []

    def derive(claims):  # the first pick is stale: "sam" is taken by now
        picks.append(claims["sub"])
        return "sam" if len(picks) == 1 else real_derive(claims)

    monkeypatch.setattr(deps, "_derive_username", derive)
    bob = client.get("/api/me", headers=auth("auth0|bob"))
    assert bob.status_code == 200
    assert bob.get_json()["username"] == "sam2"
    assert user_count(app) == 2


def test_token_without_sub_is_401(client, monkeypatch):
    import app.auth.dependencies as deps

    monkeypatch.setattr(deps, "verify_jwt", lambda token, **_: {})
    assert client.get("/api/me", headers=auth("anything")).status_code == 401


# --- recordings -------------------------------------------------------------------------------


def test_upload_then_list_shows_it(app, client):
    r = upload(client, "auth0|alice", title="  First song ", style="jazz")
    assert r.status_code == 201, r.get_json()
    saved = r.get_json()
    assert saved["title"] == "First song"
    assert saved["style"] == "jazz"
    assert saved["duration_seconds"] == pytest.approx(0.5)
    assert saved["file_url"] == f"/api/recordings/{saved['id']}/file"

    listed = client.get("/api/recordings", headers=auth("auth0|alice")).get_json()
    assert listed == [saved]


def test_file_is_stored_outside_the_db_under_user_and_recording_id(app, client, tmp_path):
    saved = upload(client, "auth0|alice").get_json()
    me = client.get("/api/me", headers=auth("auth0|alice")).get_json()

    with app.app_context():
        row = db.session.get(Recording, uuid.UUID(saved["id"]))
        assert row.file_path == f"recordings/{me['id']}/{saved['id']}.wav"
    assert (tmp_path / "storage" / row.file_path).read_bytes() == wav_bytes()


def test_owner_fetches_the_file(client):
    saved = upload(client, "auth0|alice").get_json()
    r = client.get(saved["file_url"], headers=auth("auth0|alice"))
    assert r.status_code == 200
    assert r.mimetype == "audio/wav"
    assert r.data == wav_bytes()


def test_list_is_newest_first(client):
    for title in ("one", "two", "three"):
        upload(client, "auth0|alice", title=title)
    titles = [r["title"] for r in client.get("/api/recordings", headers=auth("auth0|alice")).get_json()]
    assert titles == ["three", "two", "one"]


def test_title_and_style_are_optional(client):
    saved = upload(client, "auth0|alice").get_json()
    assert saved["title"] is None and saved["style"] is None


def test_another_user_cannot_list_or_fetch_it(client):
    saved = upload(client, "auth0|alice").get_json()

    assert client.get("/api/recordings", headers=auth("auth0|bob")).get_json() == []
    r = client.get(saved["file_url"], headers=auth("auth0|bob"))
    assert r.status_code == 404  # not 403: bob can't tell it exists
    assert r.get_json() == {"error": "Recording not found."}


def test_unknown_id_is_404(client):
    client.get("/api/me", headers=auth("auth0|alice"))
    assert client.get(f"/api/recordings/{uuid.uuid4()}/file", headers=auth("auth0|alice")).status_code == 404
    assert client.get("/api/recordings/not-a-uuid/file", headers=auth("auth0|alice")).status_code == 404


def test_deleting_a_user_deletes_their_recordings(app, client):
    upload(client, "auth0|alice")
    with app.app_context():
        db.session.delete(db.session.execute(db.select(User)).scalar_one())
        db.session.commit()
        assert db.session.scalar(db.select(db.func.count()).select_from(Recording)) == 0


@pytest.mark.parametrize(
    "kwargs, message",
    [
        ({"filename": "notes.txt"}, "Unsupported file type"),
        ({"filename": "noextension"}, "Unsupported file type"),
        ({"data": b""}, "empty"),
        ({"title": "x" * 201}, "'title'"),
        ({"style": "x" * 33}, "'style'"),
    ],
)
def test_bad_uploads_are_400_and_store_nothing(app, client, tmp_path, kwargs, message):
    r = upload(client, "auth0|alice", **kwargs)
    assert r.status_code == 400
    assert message in r.get_json()["error"]
    assert client.get("/api/recordings", headers=auth("auth0|alice")).get_json() == []
    assert not [p for p in (tmp_path / "storage").rglob("*") if p.is_file()]


def test_upload_without_a_file_is_400(client):
    r = client.post("/api/recordings", data={"title": "x"}, headers=auth("auth0|alice"),
                    content_type="multipart/form-data")
    assert r.status_code == 400


def test_too_large_upload_is_413_json(app, client):
    app.config["MAX_CONTENT_LENGTH"] = 1024
    r = upload(client, "auth0|alice", data=b"\0" * 4096)
    assert r.status_code == 413
    assert "too large" in r.get_json()["error"]


def test_unreadable_audio_is_kept_with_unknown_duration(client):
    saved = upload(client, "auth0|alice", data=b"not really webm", filename="song.webm").get_json()
    assert saved["duration_seconds"] is None


def test_file_missing_on_disk_is_404(client, tmp_path):
    saved = upload(client, "auth0|alice").get_json()
    for path in (tmp_path / "storage").rglob("*.wav"):
        path.unlink()
    r = client.get(saved["file_url"], headers=auth("auth0|alice"))
    assert r.status_code == 404
    assert "missing" in r.get_json()["error"]


# --- unauthenticated --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "method, path",
    [
        ("GET", "/api/me"),
        ("GET", "/api/recordings"),
        ("POST", "/api/recordings"),
        ("GET", f"/api/recordings/{uuid.uuid4()}/file"),
    ],
)
def test_unauthenticated_is_401(app, client, method, path):
    r = client.open(path, method=method)
    assert r.status_code == 401
    assert r.get_json()["code"] == "authorization_header_missing"
    assert user_count(app) == 0


# --- storage ----------------------------------------------------------------------------------


def test_storage_refuses_keys_outside_its_directory(tmp_path):
    from app.storage import LocalStorage

    with pytest.raises(ValueError):
        LocalStorage(tmp_path).save(io.BytesIO(b"x"), "../escape.wav")
