"""SQLAlchemy models for the ECKO application data (stored in TigerData / Tiger Cloud).

Architectural rule: Auth0 owns identity. We NEVER store passwords here.
Every application user is linked to an Auth0 identity through `auth0_id`
(the Auth0 "sub" claim, e.g. "auth0|abc123").

Audio files live outside the database (see app/storage.py); a recording row
only keeps where its file is. A user's recordings are private to them unless
they attach one to a post, which shares it with everyone signed in.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import UniqueConstraint

from app.extensions import db


def _utcnow():
    return datetime.now(timezone.utc)


def _iso(moment):
    """ISO 8601 with the UTC offset. Postgres keeps it; SQLite (the tests) drops it, so put it back."""
    if moment is None:
        return None
    return (moment if moment.tzinfo else moment.replace(tzinfo=timezone.utc)).isoformat()


class User(db.Model):
    __tablename__ = "users"

    # Generated by the app, so it's known before the row is written. The user's unique id.
    id = db.Column(db.Uuid, primary_key=True, default=uuid.uuid4)
    # Auth0 "sub" claim: the link between the authenticated person and app data.
    auth0_id = db.Column(db.String(255), unique=True, nullable=False, index=True)
    # The public face in the discussion hub. Seeded from the token on first login.
    username = db.Column(db.String(80), unique=True, nullable=False, index=True)
    display_name = db.Column(db.String(120))
    avatar_url = db.Column(db.String(512))
    created_at = db.Column(db.DateTime(timezone=True), default=_utcnow, nullable=False)

    recordings = db.relationship(
        "Recording", back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )
    posts = db.relationship("Post", back_populates="user", cascade="all, delete-orphan", passive_deletes=True)
    comments = db.relationship("Comment", back_populates="user", cascade="all, delete-orphan", passive_deletes=True)
    likes = db.relationship("PostLike", back_populates="user", cascade="all, delete-orphan", passive_deletes=True)

    def to_dict(self):
        """The signed-in user's own view (GET /api/me)."""
        return {
            "id": str(self.id),
            "auth0_id": self.auth0_id,
            "created_at": _iso(self.created_at),
            "username": self.username,
            "display_name": self.display_name,
            "avatar_url": self.avatar_url,
        }

    def to_public_dict(self):
        """What other users see: no ids, no Auth0 identity."""
        return {
            "username": self.username,
            "display_name": self.display_name,
            "avatar_url": self.avatar_url,
            "joined_at": _iso(self.created_at),
        }

    def __repr__(self):
        return f"<User {self.id} ({self.auth0_id})>"


class Recording(db.Model):
    """A finished, generated song the user chose to keep. Never the raw hum."""

    __tablename__ = "recordings"

    id = db.Column(db.Uuid, primary_key=True, default=uuid.uuid4)
    user_id = db.Column(
        db.Uuid, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Where the output audio is, as a storage key relative to STORAGE_DIR
    # (e.g. "recordings/<user_id>/<recording_id>.wav"), not an absolute path.
    file_path = db.Column(db.String(1024), nullable=False)
    title = db.Column(db.String(200))
    style = db.Column(db.String(32))
    duration_seconds = db.Column(db.Float)
    created_at = db.Column(db.DateTime(timezone=True), default=_utcnow, nullable=False)

    user = db.relationship("User", back_populates="recordings")
    posts = db.relationship("Post", back_populates="recording")

    def to_dict(self):
        return {
            "id": str(self.id),
            "title": self.title,
            "style": self.style,
            "duration_seconds": self.duration_seconds,
            "created_at": _iso(self.created_at),
            "file_url": f"/api/recordings/{self.id}/file",
        }

    def __repr__(self):
        return f"<Recording {self.id} of user {self.user_id}>"


class Post(db.Model):
    __tablename__ = "posts"

    id = db.Column(db.Uuid, primary_key=True, default=uuid.uuid4)
    user_id = db.Column(
        db.Uuid, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Optional: a post may showcase one of the author's recordings, which shares it.
    recording_id = db.Column(
        db.Uuid, db.ForeignKey("recordings.id", ondelete="SET NULL"), nullable=True
    )
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False, default="")
    created_at = db.Column(db.DateTime(timezone=True), default=_utcnow, nullable=False)
    updated_at = db.Column(
        db.DateTime(timezone=True), default=_utcnow, onupdate=_utcnow, nullable=False
    )

    user = db.relationship("User", back_populates="posts")
    recording = db.relationship("Recording", back_populates="posts")
    comments = db.relationship("Comment", back_populates="post", cascade="all, delete-orphan", passive_deletes=True)
    likes = db.relationship("PostLike", back_populates="post", cascade="all, delete-orphan", passive_deletes=True)

    def to_dict(self, include_comments=False):
        data = {
            "id": str(self.id),
            "title": self.title,
            "content": self.content,
            "author": self.user.to_public_dict() if self.user else None,
            "recording": None,
            "like_count": len(self.likes),
            "comment_count": len(self.comments),
            "created_at": _iso(self.created_at),
            "updated_at": _iso(self.updated_at),
        }
        if self.recording:
            data["recording"] = {
                "id": str(self.recording.id),
                "title": self.recording.title,
                "style": self.recording.style,
                "duration_seconds": self.recording.duration_seconds,
                # Through the post, not /api/recordings/<id>/file, which only the owner may use.
                "audio_url": f"/api/posts/{self.id}/audio",
            }
        if include_comments:
            data["comments"] = [c.to_dict() for c in sorted(self.comments, key=lambda c: c.created_at)]
        return data


class Comment(db.Model):
    __tablename__ = "comments"

    id = db.Column(db.Uuid, primary_key=True, default=uuid.uuid4)
    post_id = db.Column(
        db.Uuid, db.ForeignKey("posts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id = db.Column(
        db.Uuid, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), default=_utcnow, nullable=False)

    post = db.relationship("Post", back_populates="comments")
    user = db.relationship("User", back_populates="comments")

    def to_dict(self):
        return {
            "id": str(self.id),
            "content": self.content,
            "author": self.user.to_public_dict() if self.user else None,
            "created_at": _iso(self.created_at),
        }


class PostLike(db.Model):
    __tablename__ = "post_likes"
    __table_args__ = (
        # A user can't like the same post twice.
        UniqueConstraint("post_id", "user_id", name="uq_post_like"),
    )

    id = db.Column(db.Uuid, primary_key=True, default=uuid.uuid4)
    post_id = db.Column(
        db.Uuid, db.ForeignKey("posts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id = db.Column(
        db.Uuid, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    created_at = db.Column(db.DateTime(timezone=True), default=_utcnow, nullable=False)

    post = db.relationship("Post", back_populates="likes")
    user = db.relationship("User", back_populates="likes")
